## Cálculo do gradiente

In [1]:
import numpy as np

**Calculo da Sigmoide**

In [2]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

**Derivada da função sigmóide**

In [3]:
def sigmoid_prime(x):
        return sigmoid(x) * (1 - sigmoid(x))

**Definições iniciais**

In [4]:
learnrate = 0.5                     #Taxa de aprendizado
x = np.array([1, 2, 3, 4])          #Vetor de entrada da Rede
y = np.array(0.5)                   #Valor de Saida esperado
b = 0.5                             #Bias, valor de ativação do neuronio

**Pesos Iniciais**

In [5]:
w = np.array([0.5, -0.5, 0.3, 0.1])

**Produto escalar das entradas e pesos da rede**

In [6]:
h = np.dot(x, w)+b

**Calculo das saidas da rede Neural**

In [7]:
nn_output = sigmoid(h)
print(nn_output)

0.7858349830425586


**Erro da rede neural**

In [8]:
error = y - nn_output

**Termo de erro**

In [9]:
error_term = error * sigmoid_prime(h)

**Alteração nos pesos**

In [10]:
del_w = learnrate * error_term * x

In [11]:
print(del_w)

[-0.02405278 -0.04810556 -0.07215834 -0.09621112]


**Vetor original de entrada + delta = vetor da próxima iteração**

In [12]:
w = w + del_w

**Vetor de pesos atualizado**

In [13]:
print(w)

[ 0.47594722 -0.54810556  0.22784166  0.00378888]


**Saidas**

In [14]:
print("Saida da Rede Neural:")
print(nn_output)
print("Tamanho do erro:")
print(error)
print("Alterações nos pesos:")
print(del_w)

Saida da Rede Neural:
0.7858349830425586
Tamanho do erro:
-0.2858349830425586
Alterações nos pesos:
[-0.02405278 -0.04810556 -0.07215834 -0.09621112]
