## Configuração da MPL

In [1]:
#Importando a biblioteca
import numpy as np

#Função do cáculo da sigmóide
def sigmoid(x):
    return 1/(1+np.exp(-x))

#Arquitetura da MPL
N_input = 3     #Numero de neuronios na camada de entrada
N_hidden = 4    #Numero de neuronios na camada oculta
N_output = 2    #Numero de neuronios na camada de saida

#Vetor dos valores de entrada
x = np.array([0.5, 0.1, -0.2])
target = np.array([0.3, 0.8])   # Saida Esperada
learnrate = 0.5                 # Taxa de aprendizado

#Pesos da Camada Oculta

weights_input_hidden = np.array([[-0.08,  0.08, -0.03, 0.03],
                                 [ 0.05,  0.10,  0.07, 0.02],
                                 [-0.07,  0.04, -0.01, 0.01]])

#Cada neuronio da camada de entrada está ligado
#com todos os neuronios da camada oculta, totalizando 12 conexões, e consequentemente 12 pesos, como na matriz 3x4 acima onde,
#cada coluna representa as 3 conexões dos neuronios de entrada com o neuronio oculto (n_hidden).
#O indice é dado por: i[n_in][n_hidden] sendo:
#i = indice
#n_in = neuronio de entrada
#n_hidden = neuronio da camada oculta



#Pesos da Camada de Saída
weights_hidden_output = np.array([[-0.18,  0.11],
                                  [-0.09,  0.05],
                                  [-0.04,  0.05],
                                  [-0.02,  0.07]])

#Cada neuronio da camada oculta está ligado
#com todos os neuronios da camada de saida, totalizando 8 conexões, e consequentemente 8 pesos, como na matriz 4x2 acima onde,
#cada coluna representa as 4 conexões dos neuronios ocultos com o neuronio de saida(n_output).
#O indice é dado por: i[n_hidden][n_output] sendo:
#i = indice
#n_hidden = neuronio da camada oculta
#n_output = neuronio de saida



### Forward Pass

In [2]:
#Camada oculta

#Combinação linear(Produto escalar) de entradas e pesos sinápticos (Camada de entrada -> Camada Oculta)
hidden_layer_input = np.dot(x, weights_input_hidden)
#Aplicado a função de ativação na camada oculta
hidden_layer_output = sigmoid(hidden_layer_input)

#Camada de Saída

#Combinação linear(Produto escalar) de entradas e pesos sinápticos (Camada Oculta -> Camada de Saida)
output_layer_in = np.dot(hidden_layer_output, weights_hidden_output)

#Aplicado a função de ativação na camada de saida
output = sigmoid(output_layer_in)

print('As saídas da rede são',output)


As saídas da rede são [0.45883963 0.53497652]


## Backward Pass

In [3]:

#Cálculo do Erro
error = target - output

#Calcule o termo de erro de saída (Gradiente da Camada de Saída)
output_error_term = error * output * (1 - output)

#Calcule a contribuição da camada oculta para o erro]
#hidden_error é dado pelo Produto Escalar dos pesos de saida da camada oculta e a saida final da rede
hidden_error = np.dot(weights_hidden_output,output_error_term)


#Calcule o termo de erro da camada oculta (Gradiente da Camada Oculta)
#hidden_error_term é dado pelo produto escalar calculado anteriormente multiplicado pela derivada da função de ativação
hidden_error_term = hidden_error * hidden_layer_output * (1 - hidden_layer_output)


#Calcule a variação do peso da camada de saída
#O delta dos pesos de saida da camada oculta é proporcional a influencia dos pesos
delta_w_h_o = learnrate * output_error_term*hidden_layer_output[:, None]
print('delta_w_h_o: ',delta_w_h_o)

#Calcule a variação do peso da camada oculta
#O delta dos pesos de entrada da camada oculta é proporcional a influencia dos pesos
delta_w_i_h = learnrate * hidden_error_term * x[:, None]
print('delta_w_i_h: ',delta_w_i_h)



[-0.03944081  0.06593165]
delta_w_h_o:  [[-0.00975667  0.01630985]
 [-0.01006724  0.016829  ]
 [-0.00983062  0.01643346]
 [-0.00993415  0.01660653]]
delta_w_i_h:  [[ 8.96890297e-04  4.27702305e-04  3.04635689e-04  3.37732992e-04]
 [ 1.79378059e-04  8.55404611e-05  6.09271378e-05  6.75465983e-05]
 [-3.58756119e-04 -1.71080922e-04 -1.21854276e-04 -1.35093197e-04]]


### Atualização dos Pesos

In [4]:
weights_input_hidden = learnrate * delta_w_i_h
print('weights_input_hidden: ',weights_input_hidden)
weights_hidden_output = learnrate * delta_w_h_o
print('weights_hidden_output: ',weights_hidden_output)

weights_input_hidden:  [[ 4.48445149e-04  2.13851153e-04  1.52317845e-04  1.68866496e-04]
 [ 8.96890297e-05  4.27702305e-05  3.04635689e-05  3.37732992e-05]
 [-1.79378059e-04 -8.55404611e-05 -6.09271378e-05 -6.75465983e-05]]
weights_hidden_output:  [[-0.00487834  0.00815492]
 [-0.00503362  0.0084145 ]
 [-0.00491531  0.00821673]
 [-0.00496708  0.00830327]]
