# NumPy 


O NumPy é uma Biblioteca de Álgebra Linear para Python, o motivo pelo qual é tão importante para a Ciência de Dados com Python é que quase todas as bibliotecas do Ecossistema PyData confiam no NumPy como um de seus principais blocos de construção.

O Numpy também é rápido, pois possui ligações para as bibliotecas C. Para obter mais informações sobre por que você gostaria de usar matrizes em vez de listas, confira em [StackOverflow post](http://stackoverflow.com/questions/993984/why-numpy-instead-of-python-lists).

## Instruções de instalação

É altamente recomendável instalar o Python usando a distribuição Anaconda para garantir que todas as dependências subjacentes (como as bibliotecas de álgebra linear) sejam sincronizadas com o uso de uma instalação conda. Se você possui o Anaconda, instale o NumPy acessando o terminal ou prompt de comando e digitando:
    
    conda install numpy
    
**Se você não possui o Anaconda e não pode instalá-lo, consulte a documentação oficial do Numpy em várias instruções de instalação.(http://docs.scipy.org/doc/numpy-1.10.1/user/install.html)**

## Usando NumPy

Depois de instalar o NumPy, você pode importá-lo como uma biblioteca:

In [1]:
import numpy as np

O Numpy possui muitas funções e recursos internos. Não abordaremos todos eles, mas focaremos alguns dos aspectos mais importantes do Numpy: vetores, matrizes, matrizes e geração de números. Vamos começar discutindo matrizes.

# Numpy Arrays

As matrizes NumPy são a principal maneira de usarmos o Numpy ao longo do curso. Matrizes numpy vêm basicamente em dois sabores: vetores e matrizes. Os vetores são estritamente matrizes 1-d e matrizes são 2-d (mas você deve observar que uma matriz ainda pode ter apenas uma linha ou uma coluna).

Vamos começar nossa introdução explorando como criar matrizes NumPy.

## Criando matrizes NumPy

### De uma lista Python

Podemos criar uma matriz convertendo diretamente uma lista ou lista de listas:

In [3]:
my_list = [1,2,3]
my_list

[1, 2, 3]

In [4]:
np.array(my_list)

array([1, 2, 3])

In [5]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [6]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Métodos internos

Existem várias maneiras internas de gerar matrizes


### arange

Retorne valores espaçados uniformemente dentro de um determinado intervalo.

In [2]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])


### zeros e uns

Gere matrizes de zeros ou uns

In [4]:
np.zeros(3)

array([0., 0., 0.])

In [5]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [6]:
np.ones(3)

array([1., 1., 1.])

In [7]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### linspace

Retornar números espaçados uniformemente em um intervalo especificado.

In [9]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [10]:
np.linspace(0,10,50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

## eye


Cria uma matriz de identidade

In [11]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Random 

O Numpy também tem várias maneiras de criar matrizes de números aleatórios:

### rand
Crie uma matriz da forma especificada e preencha-a com
amostras aleatórias de uma distribuição uniforme
sobre `` [0, 1) ``.

In [12]:
np.random.rand(2)

array([0.39475431, 0.89922528])

In [13]:
np.random.rand(5,5)

array([[0.49188097, 0.79932292, 0.09250795, 0.07198974, 0.47417033],
       [0.33205635, 0.52488067, 0.59224479, 0.81157403, 0.41029343],
       [0.00331965, 0.98806717, 0.66578388, 0.73370044, 0.15458728],
       [0.036294  , 0.19063188, 0.39244472, 0.42211163, 0.6672625 ],
       [0.56707613, 0.22849278, 0.1632148 , 0.95464585, 0.5627588 ]])

### randn


Retorne uma amostra (ou amostras) da distribuição "normal normal". Ao contrário do rand, que é uniforme:

In [14]:
np.random.randn(2)

array([ 0.55124133, -1.39977036])

In [15]:
np.random.randn(5,5)

array([[ 1.87709148,  1.21236074, -0.23992732,  0.66170163,  0.25844646],
       [ 1.52812156, -0.09105485, -0.18249182, -1.15604773, -0.66219923],
       [ 0.17090623, -0.04831983,  0.76479797, -1.64640056,  1.41033163],
       [ 0.45535758,  2.09938468, -0.60183196,  1.73775285,  0.9436814 ],
       [ 0.02424766, -0.41855243,  1.19446959,  1.07618018, -0.38759195]])

### randint
Retorne números inteiros aleatórios de `baixo` (inclusive) para` alto` (exclusivo).

In [16]:
np.random.randint(1,100)

73

In [17]:
np.random.randint(1,100,10)

array([54, 86, 25, 96, 52, 68, 79, 30, 23, 11])


## Atributos e métodos de matriz

Vamos discutir alguns atributos e métodos úteis ou uma matriz:

In [25]:
arr = np.arange(25)
ranarr = np.random.randint(0,50,10)

In [26]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [20]:
ranarr

array([ 5, 43, 27, 18, 39,  7, 40, 28, 38, 46])

## Reshape
Retorna uma matriz que contém os mesmos dados com uma nova forma.

In [27]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### max,min,argmax,argmin

Estes são métodos úteis para encontrar valores máximos ou mínimos. Ou para encontrar seus locais de índice usando argmin ou argmax

In [28]:
ranarr

array([39, 24, 27, 34,  2, 33, 44,  8,  5, 24])

In [29]:
ranarr.max()

44

In [30]:
ranarr.argmax()

6

In [31]:
ranarr.min()

2

In [32]:
ranarr.argmin()

4

## Shape

Shape is an attribute that arrays have (not a method):

In [33]:
# Vector
arr.shape

(25,)

In [34]:
# Notice the two sets of brackets
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [35]:
arr.reshape(1,25).shape

(1, 25)

In [36]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [37]:
arr.reshape(25,1).shape

(25, 1)

### dtype


Você também pode pegar o tipo de dados do objeto na matriz:

In [38]:
arr.dtype

dtype('int32')


# Bom trabalho!